### ISSUE TITLE
Check Verenas Project Plan

### ISSUE THREAD

**Issue by strubrina** [strubrina/WEEM#15]
GanttDue: 2021-11-26
GanttStart: 2021-11-22

- [x] Checked by Helena
- [x] Checked by Michael
- [x] Checked by Sabrina

The last one closes the issues please :)
